slug = "issue-4"
number = 4
title = "Issue 4"
cover = "/static/ferris/4.jpeg"
pub_date = "2023-06-05"
publish = true

[[article]]
file = "show.md"
title = "Show Magazine #1"
author = "rust-magazine"
topic = ["show-magazine"]
pub_date = "2023-05-26"
publish = true
featured = true

[[article]]
file = "jhpratt.md"
title = "Interview with @jhpratt"
author = ["folyd", "jhpratt"]
topic = ["interview"]
pub_date = "2023-05-27"
publish = true
featured = true

[[article]]
file = "rust-pin-advanced.md"
title = "Rust Pin in advanced"
author = "folyd"
topic = ["tutorial"]
pub_date = "2023-07-27"
publish = false
featured = true
